2018-03-19 15:04:45.036862: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-03-19 15:04:45.614433: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:09:00.0
totalMemory: 5.93GiB freeMemory: 5.86GiB
2018-03-19 15:04:45.614678: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:09:00.0, compute capability: 6.1)
2018-03-19 15:05:00.622636: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.62GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-03-19 15:05:00.622985: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:00.964216: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.96GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-03-19 15:05:01.326182: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.64GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-03-19 15:05:03.504936: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.62GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-03-19 15:05:03.505263: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:05.396823: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.62GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-03-19 15:05:05.397123: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:07.271849: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.62GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-03-19 15:05:07.272147: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:09.137623: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.62GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-03-19 15:05:09.137918: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:11.035052: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.62GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-03-19 15:05:11.035401: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:12.896195: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.62GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-03-19 15:05:12.896514: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:14.772792: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.62GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-03-19 15:05:14.773137: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:16.640903: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:18.502136: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:21.218490: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:23.123262: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:24.964072: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:26.809860: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:28.660221: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:30.505442: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:32.350982: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:34.213061: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:36.063610: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:37.917141: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:40.215853: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:42.077495: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:43.925623: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:45.773504: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:47.623869: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:49.477563: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:51.332454: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:53.194646: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:55.044207: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: conv2/biases_1
	 [[Node: conv2/biases_1 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2/biases_1/tag, conv2/biases/read/_17)]]
2018-03-19 15:05:55.045515: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2018-03-19 15:05:55.046234: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: conv2/biases_1
	 [[Node: conv2/biases_1 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2/biases_1/tag, conv2/biases/read/_17)]]
2018-03-19 15:05:55.046724: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: conv2/biases_1
	 [[Node: conv2/biases_1 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2/biases_1/tag, conv2/biases/read/_17)]]
2018-03-19 15:05:55.046974: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: conv2/biases_1
	 [[Node: conv2/biases_1 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2/biases_1/tag, conv2/biases/read/_17)]]
/home/s1446364/miniconda3/envs/mlp/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Traceback (most recent call last):
  File "/home/s1446364/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/s1446364/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/s1446364/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: conv2/biases_1
	 [[Node: conv2/biases_1 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2/biases_1/tag, conv2/biases/read/_17)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_cifar.py", line 60, in <module>
    feed_dict={left:b_l, right:b_r, label: b_sim})
  File "/home/s1446364/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/s1446364/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/s1446364/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/s1446364/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: conv2/biases_1
	 [[Node: conv2/biases_1 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2/biases_1/tag, conv2/biases/read/_17)]]

Caused by op 'conv2/biases_1', defined at:
  File "train_cifar.py", line 51, in <module>
    tf.summary.histogram(var.op.name, var)
  File "/home/s1446364/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/summary/summary.py", line 192, in histogram
    tag=tag, values=values, name=scope)
  File "/home/s1446364/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 188, in _histogram_summary
    "HistogramSummary", tag=tag, values=values, name=name)
  File "/home/s1446364/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/s1446364/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/s1446364/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Nan in summary histogram for: conv2/biases_1
	 [[Node: conv2/biases_1 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2/biases_1/tag, conv2/biases/read/_17)]]

